### ISSUE TITLE
fitness u nejhorsiho tanku = 0 ?

### ISSUE THREAD

**Issue by ogajduse** [ogajduse/robocode-genetic-algorithms#7]
Divam se do kodu a mam trochu nejasnosti v tom jestli fitness nejlepsiho tanku se ma blizit k nule nebo k nekonecnu. My to delame tak ze by bereme skore primo jako fitness. Tedy, kdyz je skore = 0 , tak fitness=0 taky. Takze nejhorsi tank ma fitness = 0. Je to spravne? Ja si nemyslim.
@rligocki

**Comment by rligocki** [comment]
Mělo by to tak být. Všiml jsem si, že mi to nějak konverguje k 0 score .. ty tanky se pořad zhoršuji
